### ISSUE TITLE
Provide templates as python modules/packages

### ISSUE THREAD

**Issue by gunnarx** [COVESA/ifex#36]
Suggested by @miketsukerman in #32:  Noted here for further discussion.

Templates could also be a python module on its own. In theory, one can think of the small python wrapper over templates (if we will come up with some API) and vscgen then would just load them by name.

```
pip3 install vsc-templates-someip-cpp
vscgen seats.yaml vsc-templates-someip-cpp

```
Where vscgen would then try to import vsc-templates-someip-cpp internally in the runtime to get the list of templates and run the generator.

**Comment by gunnarx** [comment]
Discussed briefly on some previous meeting.   

I there mentioned that I believe it's more likely that complex generation tools will need to provide not only a jinja template, but also their own custom python code. 

1) Even if it is possible to embed conditional expressions, loops, etc. in jinja templates themselves, it should be clear that complex code in a separate python file is a lot more readable and nicer to work with, **if** a complex logic is required to be implemented.
2) Things like configuration and command-line argument parsing will probably be unique to the custom generator anyway.

For that reason I propose the answer is that we are unlikely to provide only a jinja template as a python module, but a "complete tool" of some sort might be useful to distribute as a separate package.  I will include python, jinja, docs, etc.  

(In case something only needs to include a jinja template that's fine too of course.  The more general case covers that specific situation too.  There's probably not so much more to discuss on this topic).

**Comment by gunnarx** [comment]
Please let me know if you agree.  If there are no other comments / opinions I think we will close this issue soon.

**Comment by gunnarx** [comment]
There has been a lot of rework here.   

I introduced TemplateDir and JinjaTemplateEnv as wrappers around the template handling.   I would note that they are still using some module-level variables so they can't really be instantiated more than once.  It is  working, as long as we execute serially (no multi-threading etc).    There are functions to set new values on the module-level variables such as "set template directory" so that it can be reused, in a serial fashion.  The design doesn't feel completely clean but it's about continuous improvement here.

Putting that aside, I don't at the moment see a need to provide templates (or a specific code generator) as individual installable modules.   For now we are developing _all_ features (different output types for example) within one project / package at least a while longer, in my opinion.    The latest code has at least better support for multiple output types by putting them each in their own directory, and automatically matching node types to individual templates.

**Comment by gunnarx** [comment]
If it's OK I would close this ticket, at least for now, @miketsukerman ?

**Comment by miketsukerman** [comment]
You can close this ticket, no problem. 

>> I introduced TemplateDir and JinjaTemplateEnv as wrappers around the template handling.
I need to revise what has changed in the implementation since November.
