### ISSUE TITLE
Do we want to rename namespaces to interfaces?

### ISSUE THREAD

**Issue by magnusfeuer** [COVESA/ifex#73]
Now that versioning has been added to namespaces, that name starts to feel a bit awkward.

Shall we harmonize with FrancaIDL and rename them interfaces?

**Comment by gunnar-mb** [comment]
The concept of an **interface:** node has now been added to the internal model, and documented in the specification.
Namespaces remain.  See specification for their relationship.  
_N.B. The IFEX core IDL specification is still open to feedback/discussion and possible modification (preferably backwards compatible, but everything is possible to discuss!).  Feedback is welcome._

**Comment by gunnar-mb** [comment]
> While talking about namespaces/interfaces, I think it could be good to consider how potential VSS mapping could affect that. 

Agree. There are a few comments in [IFEX and VSS Interoperability](https://github.com/COVESA/ifex/blob/master/docs/static-vss_integration_proposal.md) about it. 
Further discussion I propose should happen in a CVI or VSS project context.  If it shall be part of IFEX project, let's open a separate ticket for it.
