### ISSUE TITLE
Create range expression grammar file

### ISSUE THREAD

**Issue by magnusfeuer** [COVESA/ifex#79]
Create lark grammar that generates a parse tree for range expressions.

**Comment by gunnar-mb** [comment]
I agree with the need to work on this topic.  I would like to generalize it from "range" to "_type constraints_".  An appropriately designed strategy and syntax for applying _constraints_ on types should be developed (in other words defining the allowed values of any data type).  It would include range-limits but might also be able to do more.  It is an open design topic.

**Comment by gunnar-mb** [comment]
Closing since it is too narrow and specific, and #78 will track the creation of a new strategy first.
